permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: BB的博客
  email: iroben@163.com
  link: http://liuzijin.cn
  weibo: http://weibo.com/u/2590456590
  github: http://github.com/iroben

# 站点信息
title: BB的博客 
description: BB的博客
url: http://liuzijin.cn
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://avatars0.githubusercontent.com/u/2619250?v=3&u=d1ff24a9866d19088c64621ebe3c58d1f0279c70&s=140
favicon: https://avatars0.githubusercontent.com/u/2619250?v=3&u=d1ff24a9866d19088c64621ebe3c58d1f0279c70&s=140

# google analytics 设置
ga:
  id: UA-72704745-1
  url: liuzijin.cn

# disqus 设置
disqus:
  shortname: BB
